#version 460
#extension GL_EXT_ray_tracing : require

layout(set=0,binding=0) uniform accelerationStructureEXT topLevelAS;
layout(set=0,binding=1, std430) buffer Params { vec4 origin; vec4 direction; float tmin; float tmax; uint result; } params;
layout(location=0) rayPayloadEXT uint hit;
void main(){
  uint flags=gl_RayFlagsOpaqueEXT; uint mask=0xffu; hit=0u;
  traceRayEXT(topLevelAS, flags, mask, 0, 0, 0, params.origin.xyz, params.tmin, params.direction.xyz, params.tmax, 0);
  params.result = hit;
}

